# Generated by Django 5.1.6 on 2025-03-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Can view all mailings"),
                    ("can_view_all_users", "Can view all recipients"),
                    ("can_block_users", "Can block users"),
                    ("can_disable_mailings", "Can disable mailings"),
                ]
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
