# Generated by Django 5.1.6 on 2025-02-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="Ф.И.О.")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Комментарий"),
                ),
            ],
        ),
    ]
