# Generated by Django 5.1.6 on 2025-02-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
