# Generated by Django 5.1.6 on 2025-03-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(max_length=10, verbose_name="Статус"),
        ),
    ]
