# Generated by Django 5.1.6 on 2025-02-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_recipient_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
