# Generated by Django 5.1.6 on 2025-02-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_mailing"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
