# Generated by Django 5.1.6 on 2025-02-12 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0006_mailing_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_at",
            field=models.DateTimeField(verbose_name="Дата и время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_sent_at",
            field=models.DateTimeField(verbose_name="Дата и время первой отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="newsletter.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                to="newsletter.recipient", verbose_name="Получатели"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                default="Создана",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
